import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

// The version is computed as in the app, so the browser and the phone name a build the same way.
val gitSha: Provider<String> = providers.environmentVariable("GITHUB_SHA").map { it.take(7) }
    .orElse(
        providers.exec {
            commandLine("git", "rev-parse", "--short=7", "HEAD")
            isIgnoreExitValue = true
        }.standardOutput.asText.map { it.trim().ifEmpty { "dev" } },
    )

val commitCount: Provider<String> = providers.exec {
    commandLine("git", "rev-list", "--count", "HEAD")
    isIgnoreExitValue = true
}.standardOutput.asText.map { it.trim().ifEmpty { "1" } }

/** Writes `BuildInfo.kt` (version name and build time) and the service worker with its cache name. */
abstract class GenerateBuildInfo : DefaultTask() {
    @get:Input abstract val versionName: Property<String>
    @get:Input abstract val builtAt: Property<Long>
    @get:InputFile abstract val serviceWorker: RegularFileProperty
    @get:OutputDirectory abstract val sourceDir: DirectoryProperty
    @get:OutputDirectory abstract val resourceDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val dir = sourceDir.get().asFile.resolve("fi/jukkakot/rubikkisolveri/web").apply { mkdirs() }
        dir.resolve("BuildInfo.kt").writeText(
            """
            |package fi.jukkakot.rubikkisolveri.web
            |
            |// Generated by web/build.gradle.kts (generateBuildInfo).
            |object BuildInfo {
            |    const val VERSION_NAME = "${versionName.get()}"
            |    const val BUILT_AT = ${builtAt.get()}L
            |}
            |""".trimMargin(),
        )
        val sw = serviceWorker.get().asFile.readText().replace("__VERSION__", versionName.get())
        resourceDir.get().asFile.apply { mkdirs() }.resolve("sw.js").writeText(sw)
    }
}

val generateBuildInfo = tasks.register<GenerateBuildInfo>("generateBuildInfo") {
    versionName.set(commitCount.zip(gitSha) { count, sha -> "1.0.$count-$sha" })
    // Minute precision keeps the task up to date between quick rebuilds.
    builtAt.set(System.currentTimeMillis() / 60_000 * 60_000)
    serviceWorker.set(layout.projectDirectory.file("src/sw.js"))
    sourceDir.set(layout.buildDirectory.dir("generated/buildinfo/kotlin"))
    resourceDir.set(layout.buildDirectory.dir("generated/buildinfo/resources"))
}

kotlin {
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        outputModuleName = "rubikki"
        browser {
            commonWebpackConfig { outputFileName = "rubikki.js" }
        }
        binaries.executable()
    }

    sourceSets {
        wasmJsMain {
            kotlin.srcDir(generateBuildInfo.flatMap { it.sourceDir })
            resources.srcDir(generateBuildInfo.flatMap { it.resourceDir })
            dependencies {
                implementation(project(":shared"))
                implementation(libs.kotlinx.browser)
            }
        }
    }
}
